### ISSUE TITLE
What is data in advi class?

### ISSUE THREAD

**Issue by nipunbatra** [patel-zeel/ajax#4]
Is it a matrix? How about when we have linear regression like problems with X and y.

https://github.com/patel-zeel/advi_jax/blob/4d94918171fe8001a37a6475f0678d535b4df88d/advi_jax/advi.py#L9

**Comment by patel-zeel** [comment]
The `self.data` argument is passed to the `self.likelihood_log_prob_fun`, so `likelihood_log_prob_fun` can make use of data internally. For linear regression, data should be a tuple (X, y) and `likelihood_log_prob_fun` would look like this:
```py
def likelihood_log_prob_fun(theta, data):
    noise_scale = 0.01
    X, y = data
    mean = X@theta
    scale = jnp.ones_like(y) * noise_scale
    log_probs = jax.vmap(lambda a, b, c: dist.Normal(a, b).log_prob(c), in_axes=(0,0,0))(mean, scale, y)
    return jnp.sum(log_probs)
```

Here, a challenge will be to make the `noise_scale` trainable. One way is to pass `params = {"variational_dist": variational_dist, "log_noise_scale": log_noise_scale}` to objective function and then propagate `**params` kwargs to `likelihood_log_prob_fun`:

```py
def likelihood_log_prob_fun(theta, data, **params):
    noise_scale = jnp.exp(params["log_noise_scale"])
    X, y = data
    mean = X@theta
    scale = jnp.ones_like(y) * noise_scale
    log_probs = jax.vmap(lambda a, b, c: dist.Normal(a, b).log_prob(c), in_axes=(0,0,0))(mean, scale, y)
    return jnp.sum(log_probs)
```

I did not think of this way before. I was thinking to make `noise_scale` as a normal distribution with a mean and variance along with `weights` earlier (considering it inside the variational MeanField) but it seems that we can learn a point-estimate of `noise_scale` (or any other variables) in the above-discussed way.

**Comment by patel-zeel** [comment]
This is deprecated now.
