### ISSUE TITLE
add ADVI MF vs Full rank for 2d Gauss demo to pyprobml repo

### ISSUE THREAD

**Issue by murphyk** [patel-zeel/ajax#7]
<img width="707" alt="Screen Shot 2022-07-20 at 10 40 28 PM" src="https://user-images.githubusercontent.com/4632336/180137989-8cbe3d85-5883-420e-9e82-ff7fab21ae96.png">

**Comment by patel-zeel** [comment]
Resolved by https://github.com/probml/pyprobml/pull/1081
